services:
  backend:
    build:
      context: Backend
    container_name: clinic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: clinic
    container_name: clinic-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
